services:
  ldap:
    image: docker.io/bitnami/openldap:latest
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: secret
      LDAP_ROOT: dc=example,dc=com
      LDAP_CUSTOM_LDIF_DIR: /ldif
    volumes:
      - ./ldif:/ldif
    ports:
      - 1389:1389
    restart: always
